const products=[
{id:1,name:"Sculpted Ceramic Vase",category:"Home",price:34,emoji:"🏺",tag:"Bestseller",color:"#e9dfd0",desc:"A soft silhouette for fresh stems."},
{id:2,name:"Everyday Stoneware Mug",category:"Home",price:18,emoji:"☕",tag:"Everyday",color:"#d9e3d5",desc:"Your favourite ritual, made warmer."},
{id:3,name:"Studio Desk Lamp",category:"Workspace",price:62,emoji:"💡",tag:"Popular",color:"#e8d6bd",desc:"A little glow for late ideas."},
{id:4,name:"Linen Bound Notebook",category:"Workspace",price:14,emoji:"📓",tag:"New",color:"#d7dfea",desc:"Room for the next big thought."},
{id:5,name:"Canvas Everyday Tote",category:"Accessories",price:26,emoji:"👜",tag:"Essential",color:"#e9d8d0",desc:"Carry your daily must-haves."},
{id:6,name:"Minimal Desk Clock",category:"Workspace",price:29,emoji:"⏰",tag:"Design pick",color:"#dce5d8",desc:"A quieter way to keep time."},
{id:7,name:"Soft Knit Throw",category:"Home",price:48,emoji:"🧶",tag:"Cosy pick",color:"#e9e3d7",desc:"Texture for slow afternoons."},
{id:8,name:"Everyday Bottle",category:"Accessories",price:22,emoji:"🧴",tag:"On the go",color:"#d9e2e7",desc:"Simple hydration, wherever you are."}];
const $=s=>document.querySelector(s);let cart=JSON.parse(sessionStorage.getItem("novaCart")||"{}");let toastTimer;
const money=n=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(n);
function renderProducts(){let list=products.filter(p=>(p.name+" "+p.desc).toLowerCase().includes($("#search").value.toLowerCase())&&($("#category").value==="All"||p.category===$("#category").value));if($("#sort").value==="low")list.sort((a,b)=>a.price-b.price);if($("#sort").value==="high")list.sort((a,b)=>b.price-a.price);$("#resultCount").textContent=`Showing ${list.length} of ${products.length} products`;$("#productGrid").innerHTML=list.length?list.map(p=>`<article class="product-card"><div class="product-image" style="--tile:${p.color}"><span class="tag">${p.tag}</span><span class="shape" role="img" aria-label="${p.name}">${p.emoji}</span></div><div class="product-info"><h3>${p.name}</h3><p>${p.desc}</p><div class="product-bottom"><strong>${money(p.price)}</strong><button class="add-button" data-add="${p.id}">＋ Add to bag</button></div></div></article>`).join(""):`<div class="empty-state">No products found. Try another search.</div>`}
function saveCart(){sessionStorage.setItem("novaCart",JSON.stringify(cart));renderCart();$("#cartCount").textContent=Object.values(cart).reduce((a,b)=>a+b,0)}
function add(id){cart[id]=(cart[id]||0)+1;saveCart();showToast("Added to your bag")}
function showToast(msg){const t=$("#toast");t.textContent=msg;t.classList.add("show");clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove("show"),1800)}
function renderCart(){const entries=Object.entries(cart).filter(([id,q])=>q>0);$("#cartItems").innerHTML=entries.length?entries.map(([id,q])=>{const p=products.find(x=>x.id===Number(id));return `<div class="cart-row"><div><strong>${p.name}</strong><small>${money(p.price)} each</small><div class="qty-controls"><button data-qty="${id}" data-delta="-1" aria-label="Decrease quantity">−</button><span>${q}</span><button data-qty="${id}" data-delta="1" aria-label="Increase quantity">＋</button><button data-remove="${id}" aria-label="Remove ${p.name}">×</button></div></div><strong>${money(p.price*q)}</strong></div>`}).join(""):`<div class="empty-state">Your bag is empty.<br>Add something lovely from the collection.</div>`;$("#cartTotal").textContent=money(entries.reduce((sum,[id,q])=>sum+products.find(p=>p.id===Number(id)).price*q,0))}
$("#productGrid").addEventListener("click",e=>{const b=e.target.closest("[data-add]");if(b)add(Number(b.dataset.add))});["search","category","sort"].forEach(id=>$("#"+id).addEventListener(id==="search"?"input":"change",renderProducts));$("#cartButton").addEventListener("click",()=>$("#cartDialog").showModal());$("#closeCart").addEventListener("click",()=>$("#cartDialog").close());$("#cartItems").addEventListener("click",e=>{const q=e.target.closest("[data-qty]"),r=e.target.closest("[data-remove]");if(q){const id=q.dataset.qty;cart[id]=(cart[id]||0)+Number(q.dataset.delta);if(cart[id]<=0)delete cart[id];saveCart()}if(r){delete cart[r.dataset.remove];saveCart()}});$("#checkout").addEventListener("click",()=>showToast("Demo checkout only — no payment was processed."));renderProducts();saveCart();